/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionnotes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hexor
 */
public class graph extends javax.swing.JFrame {

    Connexion conn = new Connexion();

    /**
     * Creates new form graph
     */
    public graph() {
        initComponents();
        ActualisationJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TxtFieldNum = new javax.swing.JTextField();
        TxtFieldNom = new javax.swing.JTextField();
        TxtFieldPrenom = new javax.swing.JTextField();
        ComboBranche = new javax.swing.JComboBox<>();
        TxtFieldNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButtonAjout = new javax.swing.JButton();
        ButtonSupprimer = new javax.swing.JButton();
        ButtonModifier = new javax.swing.JButton();
        ButtonActualiser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des notes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "prenom", "branche", "note"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 92, -1, 182));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gestion des notes");
        jLabel1.setMaximumSize(new java.awt.Dimension(101, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 376, 32));

        TxtFieldNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNumActionPerformed(evt);
            }
        });
        getContentPane().add(TxtFieldNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 92, 193, -1));

        TxtFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNomActionPerformed(evt);
            }
        });
        getContentPane().add(TxtFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 132, 193, -1));
        getContentPane().add(TxtFieldPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 172, 193, -1));

        ComboBranche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatique", "Physique/Chimie", "SVT", "Français", "Mathématiques", "Anglais", "Histoire/Géographie" }));
        ComboBranche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBrancheActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBranche, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 212, -1, -1));

        TxtFieldNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNoteActionPerformed(evt);
            }
        });
        getContentPane().add(TxtFieldNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 252, 193, -1));

        jLabel3.setText("id :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 95, -1, -1));

        jLabel4.setText("Nom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 135, -1, -1));

        jLabel5.setText("Prenom : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 175, -1, -1));

        jLabel6.setText("Branche :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 215, -1, -1));

        jLabel7.setText("Note :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 255, -1, -1));

        ButtonAjout.setText("Ajouter");
        ButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        ButtonSupprimer.setText("Supprimer");
        ButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        ButtonModifier.setText("Modifier");
        getContentPane().add(ButtonModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        ButtonActualiser.setText("Actualiser");
        ButtonActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualiserActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonActualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabel8.setText("Rechercher : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 68, 170, -1));

        jButton5.setText("OK");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel9.setText("Réalisé par Ugo Perniceni, Thibaut Yauy");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNumActionPerformed

    private void TxtFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNomActionPerformed

    private void TxtFieldNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNoteActionPerformed

    private void ButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAjoutActionPerformed
        String sql = "INSERT INTO eleve (numero, prenom, nom, branche, note) " + "VALUES (" + TxtFieldNum.getText() + ", '" + TxtFieldNom.getText() + "', '" + TxtFieldPrenom.getText() + "', '" + String.valueOf(ComboBranche.getSelectedItem()) + "', " + TxtFieldNote.getText() + ")";
        System.out.println("Requete :" + sql);
        try {
            conn.getStatement().executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(graph.class.getName()).log(Level.SEVERE, null, ex);
        }
        ActualisationJTable();
    }//GEN-LAST:event_ButtonAjoutActionPerformed

    private void ComboBrancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBrancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBrancheActionPerformed

    private void ButtonActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualiserActionPerformed
        ActualisationJTable();
    }//GEN-LAST:event_ButtonActualiserActionPerformed

    private void ButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSupprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int[] rows = jTable1.getSelectedRows();
        String sql;

        final int row = jTable1.getSelectedRow();

        final String valueInCell = (String) jTable1.getValueAt(row, 1);

        for (int i = 0; i < rows.length; i++) {
            sql = "DELETE FROM eleve WHERE numero = '" + jTable1.getValueAt(rows[i], 0) + "';";
            System.out.println("Requete :" + sql);
            try {
                conn.getStatement().executeUpdate(sql);
//                model.removeRow(rows[i]);
            } catch (SQLException ex) {
                Logger.getLogger(graph.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        ActualisationJTable();
    }//GEN-LAST:event_ButtonSupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualiser;
    private javax.swing.JButton ButtonAjout;
    private javax.swing.JButton ButtonModifier;
    private javax.swing.JButton ButtonSupprimer;
    private javax.swing.JComboBox<String> ComboBranche;
    private javax.swing.JTextField TxtFieldNom;
    private javax.swing.JTextField TxtFieldNote;
    private javax.swing.JTextField TxtFieldNum;
    private javax.swing.JTextField TxtFieldPrenom;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private void ActualisationJTable() {
        String sql = ("SELECT * FROM eleve");
        System.out.println("Requete :" + sql);
        try {
            int i = 1;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            ResultSet rs = conn.getStatement().executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("numero"), rs.getString("prenom"), rs.getString("Nom"), rs.getString("branche"), rs.getString("note")});
                System.out.println(rs.getString("prenom"));
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(graph.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
